# Generated by Django 4.2.2 on 2023-09-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0002_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль пользоввателя', 'verbose_name_plural': 'Профили пользователей'},
        ),
    ]
