# Generated by Django 4.2.2 on 2023-07-17 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_catalog', '0006_productspecifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productspecifications',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='api_catalog.product'),
        ),
    ]
