# Generated by Django 4.2.2 on 2023-07-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_catalog', '0007_alter_productspecifications_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='author_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
