# Generated by Django 4.2.2 on 2023-07-18 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_catalog', '0008_productreview_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreview',
            name='author_name',
        ),
        migrations.AddField(
            model_name='productreview',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productreview',
            name='author',
            field=models.CharField(max_length=100),
        ),
    ]
