# Generated by Django 4.2.2 on 2023-07-20 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_catalog', '0009_remove_productreview_author_name_productreview_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
