# Generated by Django 4.2.2 on 2023-09-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_catalog', '0011_product_datefrom_product_dateto_product_discount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
