# Generated by Django 4.2.2 on 2023-09-15 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_catalog', '0012_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryimage',
            options={'verbose_name': 'Изображение категории', 'verbose_name_plural': 'Изображения категори'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение товара', 'verbose_name_plural': 'Изоюражения товара'},
        ),
        migrations.AlterModelOptions(
            name='productreview',
            options={'verbose_name': 'Отзыв на товар', 'verbose_name_plural': 'Отзывы на товары'},
        ),
        migrations.AlterModelOptions(
            name='productspecifications',
            options={'verbose_name': 'Характеристики продукта', 'verbose_name_plural': 'Характеристики продуктов'},
        ),
    ]
