# Generated by Django 4.2.2 on 2023-08-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_order', '0004_order_total_order_cost_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_order_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
