# Generated by Django 4.2.2 on 2023-08-19 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_order', '0005_alter_order_total_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='unaccepted', max_length=100, null=True),
        ),
    ]
